export const actionType = {
    'CHANGE_CURRENT_PAGE': 'CHANGE_CURRENT_PAGE',
    'CHANGE_SEARCHING_VALUE': 'CHANGE_SEARCHING_VALUE',
    'CHANGE_LOADING_STATUS_OF_STUDENTLIST': 'CHANGE_LOADING_STATUS_OF_STUDENTLIST',
    'CHANGE_ERROR_STATUS_OF_STUDENTLIST': 'CHANGE_ERROR_STATUS_OF_STUDENTLIST',
    'UPDATELIST': 'UPDATELIST',
    'RELOAD_PAGE': 'RELOAD_PAGE'
}
