export const actionType = {
    'MOVE_TO_NEXTPAGE': 'MOVE_TO_NEXTPAGE',
    'MOVE_TO_PREVIOUSPAGE': 'MOVE_TO_PREVIOUSPAGE',
    'MOVE_EXACTLY_TO_PAGE': 'MOVE_EXACTLY_TO_PAGE',
    'INCREASE_PAGENUMBER': 'INCREASE_PAGENUMBER',
    'DECREASE_PAGENUMBER': 'DECREASE_PAGENUMBER',
    'SEARCH_STUDENT': 'SEARCH_STUDENT',
    'MODIFY_STUDENT': {
        'EDITING_IMG': 'EDITING_IMG',
        'EDITING_NAME': 'EDITING_NAME',
        'EDITING_PHONENUMBER': 'EDITING_PHONENUMBER',
        'EDITING_BIRTHDAY': 'EDITING_BIRTHDAY',
        'EDITING_DAYADMISSION': 'EDITING_DAYADMISSION',
        'EDITING_GENDER': 'EDITING_GENDER'
    },
    'ADD_STUDENT': {
        'ADDING_IMG': 'ADDING_IMG',
        'ADDING_NAME': 'ADDING_NAME',
        'ADDING_PHONENUMBER': 'ADDING_PHONENUMBER',
        'ADDING_BIRTHDAY': 'ADDING_BIRTHDAY',
        'ADDING_DAYADMISSION': 'ADDING_DAYADMISSION',
        'ADDING_GENDER': 'ADDING_GENDER',
        'CREATING_ID': 'CREATING_ID'
    }    

}