export const actionType = {
    'MOVE_TO_NEXTPAGE': 'MOVE_TO_NEXTPAGE',
    'MOVE_TO_PREVIOUSPAGE': 'MOVE_TO_PREVIOUSPAGE',
    'MOVE_EXACTLY_TO_PAGE': 'MOVE_EXACTLY_TO_PAGE',
    'INCREASE_PAGENUMBER': 'INCREASE_PAGENUMBER',
    'DECREASE_PAGENUMBER': 'DECREASE_PAGENUMBER',
    'CHANGE_SEARCHING_VALUE': 'CHANGE_SEARCHING_VALUE',
    'MODIFY_STUDENT': {
        'SAVE': 'EDIT_STUDENT'
    },
    'ADD_STUDENT': {
        'SAVE': 'SAVE_NEW_STUDENT'
    }
}
